using System;
using System.ComponentModel.DataAnnotations;

namespace BookStoreAPI.Model
{
    public class Book
    {
        [Key]
        public int Id { get; set; }  // This should be auto-generated by the database

        [Required]
        public string Title { get; set; }

        [Required]
        public string Author { get; set; }

        [Required]
        [Range(0, double.MaxValue, ErrorMessage = "Price must be a positive value")]
        public decimal Price { get; set; }

        public string Category { get; set; }

        [Required]
        public DateTime PublishedDate { get; set; }
    }
}
